#!/bin/sh

# Block commit when merge conflict markerts detected
if git diff --cached | grep -qE '^\+(<<<<<<<|=======|>>>>>>>)'; then
    echo "Error: Unresolved merge conflict markers detected in your staged changes." >&2
    exit 1
fi
exit 0
