#!/bin/sh

# Set current upstream branch
upstream="$1"

# Check if the string of the upstream branch name are main or master then ban git rebase
if [ "$upstream" = "main" ] || [ "$upstream" = "master" ]; then
    echo "Error: Rebasing directly onto public upstream '$upstream' is banned." >&2
    exit 1
fi
exit 0
